"""Stage 4: build ASS caption files with word-level karaoke highlighting."""
from __future__ import annotations

import logging
from pathlib import Path

from .utils import CaptionStyle

log = logging.getLogger("clipper.captions")

MAX_WORDS_PER_LINE = 4
MAX_LINE_SECONDS = 2.0
MAX_LINE_CHARS = 22          # rough width budget to avoid screen overflow
MAX_WORD_GAP_SECONDS = 1.0   # start a new line after a long silence
LINE_HOLD_SECONDS = 0.35     # keep the last line visible a moment longer

ALIGN = {"bottom": 2, "middle": 5, "top": 8}


def format_ass_time(seconds: float) -> str:
    """Format seconds as ASS timestamp 'H:MM:SS.CC' (centiseconds)."""
    seconds = max(0.0, seconds)
    hundredths = int(round(seconds * 100))
    hh, rem = divmod(hundredths, 360000)
    mm, rem = divmod(rem, 6000)
    ss, cs = divmod(rem, 100)
    return f"{hh}:{mm:02d}:{ss:02d}.{cs:02d}"


def escape_ass_text(text: str) -> str:
    """Sanitize text so override blocks and newlines cannot break the file.

    Literal braces are replaced rather than escaped: a bare '{' outside an
    override block starts one, and \\{ outside a block is renderer-dependent.
    """
    text = text.replace("{", "(").replace("}", ")")
    text = text.replace("\r", " ").replace("\n", " ")
    return text.strip()


def shift_words(words: list[dict], clip_start: float, clip_end: float) -> list[dict]:
    """Select words inside the clip window and shift them to clip-relative time."""
    out = []
    for w in words:
        start, end = float(w["start"]), float(w["end"])
        if end <= clip_start or start >= clip_end:
            continue
        out.append({
            "start": max(0.0, start - clip_start),
            "end": min(clip_end, end) - clip_start,
            "word": str(w["word"]),
        })
    return out


def group_words(words: list[dict]) -> list[dict]:
    """Group word dicts into caption lines (max words / seconds / chars, gap-aware)."""
    lines: list[dict] = []
    current: list[dict] = []
    current_chars = 0

    def flush():
        nonlocal current, current_chars
        if current:
            lines.append({
                "start": current[0]["start"],
                "end": current[-1]["end"],
                "words": current,
            })
            current, current_chars = [], 0

    for w in words:
        if current:
            gap = w["start"] - current[-1]["end"]
            too_long = (w["end"] - current[0]["start"]) > MAX_LINE_SECONDS
            too_many = len(current) >= MAX_WORDS_PER_LINE
            too_wide = current_chars + len(w["word"]) > MAX_LINE_CHARS
            if gap > MAX_WORD_GAP_SECONDS or too_long or too_many or too_wide:
                flush()
        current.append(w)
        current_chars += len(w["word"]) + 1
    flush()
    return lines


def _line_font_size(line: dict, base_size: int, out_w: int) -> int:
    """Shrink the font if the widest word would overflow the screen width."""
    longest = max((len(w["word"]) for w in line["words"]), default=0)
    if longest == 0:
        return base_size
    max_chars = max(int(out_w * 0.9 / (base_size * 0.55)), 1)
    if longest <= max_chars:
        return base_size
    return max(int(base_size * max_chars / longest), 18)


def build_dialogue(line: dict, style: CaptionStyle, out_w: int, min_start: float) -> str:
    """One ASS Dialogue event with \\k karaoke tags for word highlighting.

    `min_start` prevents overlap with the previous line: libass would otherwise
    stack simultaneous events vertically, making captions jump around.
    """
    fs = _line_font_size(line, style.font_size, out_w)
    prefix = f"{{\\fs{int(fs)}}}" if fs != style.font_size else ""

    start = max(line["start"], min_start)
    parts = []
    prev_end = start
    for w in line["words"]:
        duration_cs = max(int(round((w["end"] - prev_end) * 100)), 1)
        parts.append(f"{{\\k{duration_cs}}}{escape_ass_text(w['word'])}")
        prev_end = max(prev_end, w["end"])
    text = " ".join(parts)

    start_ts = format_ass_time(start)
    end_ts = format_ass_time(line["end"] + LINE_HOLD_SECONDS)
    return f"Dialogue: 0,{start_ts},{end_ts},Caption,,0,0,0,,{prefix}{text}"


def build_ass(
    words: list[dict],
    clip_start: float,
    clip_end: float,
    style: CaptionStyle,
    out_w: int = 1080,
    out_h: int = 1920,
) -> str:
    """Build a complete ASS subtitle string for one clip.

    `words` uses absolute transcript timestamps; the file is shifted so the
    clip starts at 0. The currently spoken word is drawn in highlight_color.
    """
    alignment = ALIGN.get(str(style.position).lower(), 2)
    margin_v = int(out_h * 0.14) if alignment == 2 else int(out_h * 0.06)

    header = f"""[Script Info]
; generated by clipper
ScriptType: v4.00+
PlayResX: {out_w}
PlayResY: {out_h}
WrapStyle: 2
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Caption,{style.font},{style.font_size},{style.highlight_color},{style.primary_color},&H00000000,&H80000000,0,0,0,0,100,100,0,0,1,{style.outline},1,{alignment},60,60,{margin_v},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""

    clipped = shift_words(words, clip_start, clip_end)
    lines = group_words(clipped)
    events = []
    min_start = 0.0
    for line in lines:
        events.append(build_dialogue(line, style, out_w, min_start))
        min_start = line["end"] + LINE_HOLD_SECONDS + 0.03
    log.info("built ASS with %d caption line(s)", len(events))
    return header + "\n".join(events) + "\n"


def write_ass(ass_text: str, out_path: Path) -> None:
    """Persist ASS text to disk (UTF-8 with BOM; libass on Windows prefers it)."""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8-sig") as fh:
        fh.write(ass_text)
